### ISSUE TITLE
更新计划

### ISSUE THREAD

**Issue by Ham0mer** [hamster1963/HomeDash-Backend#33]
大佬这个项目前后端以后还有更新计划吗？看起来真不错

**Comment by hamster1963** [comment]
home-dash 这个项目很多的代码都放在 nezha-dash 这个项目中了，后端的话由于自定义程度太高了，因此很难作为一个社区项目来进行开发，以后看看有什么其他的机会来重构这个项目吧。

**Comment by Ham0mer** [comment]
> home-dash 这个项目很多的代码都放在 nezha-dash 这个项目中了，后端的话由于自定义程度太高了，因此很难作为一个社区项目来进行开发，以后看看有什么其他的机会来重构这个项目吧。

好的大佬，我根据自己的需求适配一下吧
